version: "3.8"

services:
  grpc_server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "grpc_server.py"]
    ports:
      - "50051:50051"

  grpc_client:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "grpc_client.py"]
    depends_on:
      - grpc_server
      - nginx

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - grpc_server
